### ISSUE TITLE
Bombastic walker does not react to SIGINT

### ISSUE THREAD

**Issue by lulf** [trustification/trustification#237]
Using SIGINT to kill the bombastic walker does not work, as it attempts to continue on downloading the next file rather than exiting.

**Comment by jcrossley3** [comment]
Both walkers and the indexers have this issue. Easily reproduced using the compose scripts.

**Comment by ctron** [comment]
I guess we are missing a trigger from ctrl-c to terminate. Here is how that worked in the other project:

https://github.com/drogue-iot/drogue-cloud/blob/8aa49b2482442bb13d54d97a308a16f476ace203/server/src/main.rs#L972-L979

The idea was that once a task of the main loop finishes, the application shuts down. That signal handler will block until it receives that signal. When it returns, it ends the application.

IIRC actix-web does that automatically and returns it's main thread, which currently will also work (as one task completes, the app completes).

However, in cases where we don't use actix, what needs to be done manually.

**Comment by jcrossley3** [comment]
I spent some time today trying to replicate this without it being in a container and I couldn't. The release binary built by [this file](https://github.com/trustification/trustification/blob/7c99b254476a60e07fd08fed4665543dca93c829/trust/Containerfile#L21) and configured as the `EntryPoint` seems to respond fine to both SIGINT and SIGTERM. So maybe there's a problem with podman?

Does anyone know if the 10s timeout occurs when `docker-compose` is used to shut down the walkers/indexers?

I did figure out that `podman-compose -f ... kill --all` avoids the delays.

**Comment by lulf** [comment]
Fixed now @jcrossley3 ?

**Comment by ctron** [comment]
I neither reacted to SIGINT, but also not to SIGTERM. I think the latter one was what @jcrossley3 found out when using `down` instead of <kdb>Ctrl-C</kdb>.

**Comment by jcrossley3** [comment]
> Fixed now @jcrossley3 ?

Nope. Both indexers and both exporters still hang for 10 seconds each...
```
podman stop -t 10 compose_vexination-exporter_1
WARN[0010] StopSignal SIGTERM failed to stop container compose_vexination-exporter_1 in 10 seconds, resorting to SIGKILL 
compose_vexination-exporter_1
exit code: 0
podman stop -t 10 compose_bombastic-exporter_1
WARN[0010] StopSignal SIGTERM failed to stop container compose_bombastic-exporter_1 in 10 seconds, resorting to SIGKILL 
compose_bombastic-exporter_1
exit code: 0
podman stop -t 10 compose_nats_1
compose_nats_1
exit code: 0
podman stop -t 10 compose_bombastic-indexer_1
WARN[0010] StopSignal SIGTERM failed to stop container compose_bombastic-indexer_1 in 10 seconds, resorting to SIGKILL 
compose_bombastic-indexer_1
exit code: 0
podman stop -t 10 compose_vexination-indexer_1
WARN[0010] StopSignal SIGTERM failed to stop container compose_vexination-indexer_1 in 10 seconds, resorting to SIGKILL 
```
This occurs when I run this in one shell:
```
podman-compose -f compose.yaml -f compose-trustification.yaml -f compose-guac.yaml up
```
And this in another shell (both in the same dir):
```
podman-compose -f compose.yaml -f compose-trustification.yaml -f compose-guac.yaml down
```
Are you guys not seeing the same thing?

**Comment by ctron** [comment]
Here is what I get in the "down" terminal:

```
podman stop -t 10 compose_spog-ui_1
compose_spog-ui_1
exit code: 0
podman stop -t 10 compose_osv-certifier_1
compose_osv-certifier_1
exit code: 0
podman stop -t 10 compose_guac-ingestor_1
compose_guac-ingestor_1
exit code: 0
podman stop -t 10 compose_spog-api_1
compose_spog-api_1
exit code: 0
podman stop -t 10 compose_createbuckets_1
compose_createbuckets_1
exit code: 0
podman stop -t 10 compose_guac-graphql_1
compose_guac-graphql_1
exit code: 0
podman stop -t 10 compose_guac-collectsub_1
compose_guac-collectsub_1
exit code: 0
podman stop -t 10 compose_bombastic-api_1
compose_bombastic-api_1
exit code: 0
podman stop -t 10 compose_vexination-api_1
compose_vexination-api_1
exit code: 0
podman stop -t 10 compose_init-keycloak_1
compose_init-keycloak_1
exit code: 0
podman stop -t 10 compose_minio_1
compose_minio_1
exit code: 0
podman stop -t 10 compose_vexination-exporter_1
compose_vexination-exporter_1
exit code: 0
podman stop -t 10 compose_bombastic-exporter_1
compose_bombastic-exporter_1
exit code: 0
podman stop -t 10 compose_nats_1
compose_nats_1
exit code: 0
podman stop -t 10 compose_bombastic-indexer_1
compose_bombastic-indexer_1
exit code: 0
podman stop -t 10 compose_vexination-indexer_1
compose_vexination-indexer_1
exit code: 0
podman stop -t 10 compose_keycloak_1
compose_keycloak_1
exit code: 0
podman stop -t 10 compose_kafka_1
compose_kafka_1
exit code: 0
podman rm compose_spog-ui_1
compose_spog-ui_1
exit code: 0
podman rm compose_osv-certifier_1
compose_osv-certifier_1
exit code: 0
podman rm compose_guac-ingestor_1
compose_guac-ingestor_1
exit code: 0
podman rm compose_spog-api_1
compose_spog-api_1
exit code: 0
podman rm compose_createbuckets_1
compose_createbuckets_1
exit code: 0
podman rm compose_guac-graphql_1
Error: container 5a15a19bb907399c5eec3508bc0dbf2abad91922009f923332747ea9d4eb79f1 has dependent containers which must be removed before it: 2d8b5e2e419243218c0ea34562e22c43631329db1a2764fabf3c1554f1dd24b5, ab261dcf757b9594f6c8f6c6d0291c29f3c98fac912880736475bceb9485337b: container already exists
exit code: 125
podman rm compose_guac-collectsub_1
Error: container 674e6a39a4e8956343b59bacef8dfca0f3a3343f440b97081ca9dc52ecf9b563 has dependent containers which must be removed before it: 2d8b5e2e419243218c0ea34562e22c43631329db1a2764fabf3c1554f1dd24b5, ab261dcf757b9594f6c8f6c6d0291c29f3c98fac912880736475bceb9485337b: container already exists
exit code: 125
podman rm compose_bombastic-api_1
compose_bombastic-api_1
exit code: 0
podman rm compose_vexination-api_1
compose_vexination-api_1
exit code: 0
podman rm compose_init-keycloak_1
compose_init-keycloak_1
exit code: 0
podman rm compose_minio_1
compose_minio_1
exit code: 0
podman rm compose_vexination-exporter_1
compose_vexination-exporter_1
exit code: 0
podman rm compose_bombastic-exporter_1
compose_bombastic-exporter_1
exit code: 0
podman rm compose_nats_1
Error: container 89d1bc5631dc0606a3067e96b8e1eaadbfd735737c51b33a824bed6d265b37b9 has dependent containers which must be removed before it: 2d8b5e2e419243218c0ea34562e22c43631329db1a2764fabf3c1554f1dd24b5, 5a15a19bb907399c5eec3508bc0dbf2abad91922009f923332747ea9d4eb79f1, 674e6a39a4e8956343b59bacef8dfca0f3a3343f440b97081ca9dc52ecf9b563, ab261dcf757b9594f6c8f6c6d0291c29f3c98fac912880736475bceb9485337b: container already exists
exit code: 125
podman rm compose_bombastic-indexer_1
compose_bombastic-indexer_1
exit code: 0
podman rm compose_vexination-indexer_1
compose_vexination-indexer_1
exit code: 0
podman rm compose_keycloak_1
compose_keycloak_1
exit code: 0
podman rm compose_kafka_1
compose_kafka_1
exit code: 0

```

**Comment by ctron** [comment]
I think this one should be closed. It was a mix of SIGINT, SIGTERM.
